Pivot data
datasets/cpi-change pull request #2
Opened 2018-09-16 15:11 UTC by MAliNaqvi

2018-09-17 03:36 UTC, zelima requested changes
@MAliNaqvi datapackage.json also needs to be changed appropriately

2018-09-17 15:21 UTC, MAliNaqvi commented
@zelima updated the schema

2018-09-18 03:41 UTC, zelima approved these changes

2018-09-18 03:41 UTC, zelima commented
Looks good

2018-09-18 15:35 UTC, merged